name: control_movil
description: App de control de uso del movil
publish_to: 'none'
version: 0.1.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
