# Generated by Django 5.2.7 on 2025-10-16 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_package', models.CharField(max_length=255)),
                ('app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('limit_seconds', models.PositiveIntegerField(help_text='Tiempo máximo diario permitido (en segundos).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'app_package'], name='monitoring__user_id_6497f8_idx')],
                'unique_together': {('user', 'app_package')},
            },
        ),
    ]
