# Generated by Django 5.2.7 on 2025-10-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_applimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='limit_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
